###
POST http://localhost:3000/mercadopago/getPayment
Content-Type: application/json

{
    "userId": "637e7d5109002c068af42920",
    "cart": [
    {
      "_id": "637e7f00131521fc413edc9e",
      "title": "Iphone 14",
      "categorie": "637e7e193f06c4ccbc495bd0",
      "unit_price": {
        "usd": 1100
      },
      "details": [],
      "images": [],
      "quantity": 1,
      "createdAt": "2022-11-23T20:13:52.768Z",
      "updatedAt": "2022-11-23T20:13:52.768Z",
      "__v": 0
    }
  ]
}