###
GET http://localhost:3000/products

###
GET http://localhost:3000/products/637e3537e4d3f21f325db1c8

###
GET http://localhost:3000/products/byCategorie/637d957de5bc1ac0646ac38d

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Macbook Pro",
    "categorie": "637d957de5bc1ac0646ac38d",
    "price": {
        "usd": 2000
    }
}

###
POST http://localhost:3000/products/editCategorie
Content-Type: application/json

{
    "productId": "637e1e9c5bd12817fa2901c7",
    "categorieId": "637d9549e5bc1ac0646ac38a"
}