###
GET http://localhost:3000/products

###
GET http://localhost:3000/products/637e25ade9822a2a60c534da

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Iphone 14",
    "categorie": "637d9549e5bc1ac0646ac38a",
    "price": {
        "usd": 1100
    }
}

###
POST http://localhost:3000/products/editCategorie
Content-Type: application/json

{
    "productId": "637e1e9c5bd12817fa2901c7",
    "categorieId": "637d9549e5bc1ac0646ac38a"
}